### ISSUE TITLE
如何动态增加删除节点？

### ISSUE THREAD

**Issue by davichi11** [alibaba/compileflow#22]
能否像flowable，activitie一样能支持动态添加节点呢？

**Comment by kakaxiTeacher** [comment]
别问了，都不维护了，残疾产品

**Comment by xuan698400** [comment]
> 能否像flowable，activitie一样能支持动态添加节点呢？

你指的动态添加是在运行时添加节点么，可否描述的详细一点

**Comment by kakaxiTeacher** [comment]
这不是我问的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月5日(星期四) 下午5:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/compileflow] 如何动态增加删除节点？ (#22)




  
能否像flowable，activitie一样能支持动态添加节点呢？
  
你指的动态添加是在运行时添加节点么，可否描述的详细一点
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by voff12** [comment]
这个暂时当前还不支持人工工作流
